# ==========================================
# Training Loop (Step-Based)
# ==========================================
num_steps: 150000       
num_logs: 1000             
num_evals: 100                     
num_saves: 10              
batch_size: 128         
warmup_steps: 5000      
patience_steps: 5000  
warmup_prefix: true

# ==========================================
# Scheduler (Step-Based)
# ==========================================
sched: cosine
lr: 3.0e-4                    
warmup_lr: 0.0

# ==========================================
# Optimization
# ==========================================
opt: nadamw
weight_decay: 0.1
clip_grad: 5.0


# ==========================================
# Model Parameters (MobileNetV4 Small)
# ==========================================
model: mobilenetv4_conv_small
pretrained: false
num_classes: 100
img_size: 256
model_ema: true
model_ema_decay: 0.999

# ==========================================
# Dataset Parameters
# ==========================================
dataset: hfds/uoft-cs/cifar100
data_dir: ./data/cifar100
train_split: train
val_split: test
input_key: img
target_key: fine_label
dataset_download: true
balanced_mode: min
mean: [0, 0, 0]
std: [1, 1, 1]

# # ==========================================
# # Augmentation
# # ==========================================
# aa: rand-m9-mstd0.5-inc1 
# mixup: 0.8
# cutmix: 1.0
# mixup_prob: 1.0
# mixup_switch_prob: 0.5
# mixup_mode: batch
# smoothing: 0.1
# mixup_off_steps: 0      # Optional: Turn off mixup after N steps

# ==========================================
# Device & Distributed
# ==========================================
device: cuda
amp: true
amp_dtype: bfloat16
workers: 8
# pin_mem: false
# no_prefetcher: true
# no_aug: true

# ==========================================
# Logging
# ==========================================
output: ./output_cifar100_baseline_mnv4
experiment: mnv4_baseline_cifar100
log_wandb: true
wandb_project: labelmix
